// GENERATED by tools/build.py from src/camera.lsl - edit the source, not this file.
// ---------------------------------------------------------------------
// WIND - CAMERA
// A follow camera for each level: further back and higher the higher you
// glide, low over the water on the surface, and close behind you under
// the water. When diving it keeps the camera below the surface, so you
// see the underwater world instead of the surface from above.
// Setting "camera = 0" leaves the camera to you.
// ---------------------------------------------------------------------
// ---- shared helpers (src/common.lsl): only what this script uses ----
// ---- Levels -------------------------------------------------------------
integer L_GLIDE   = 0;   // above the ground

integer L_SURFACE = 1;   // on the water (just above the land where there is none)

integer L_DIVE    = 2;   // under the water

// Engine -> everyone
integer EVT_STATE    = 7100;  // str = the S_* fields joined with ","

// Config <-> everyone
integer EVT_SETTINGS = 7200;  // settings changed: read them again

integer MSG_MEMORY   = 7300;  // everyone: say how much memory you use

// ---- EVT_STATE fields ---------------------------------------------------
integer S_ACTIVE  = 0;  // 1 while Wind is on

integer S_LEVEL   = 1;  // L_*

integer S_WATER   = 3;  // Glide/Surface: water is what is below you. Dive: always 1

integer S_HEIGHT  = 4;  // Glide height setting, whole metres

integer S_BOOST   = 6;  // 1 while boosting (double-tap W and hold)

// The last EVT_STATE, for the scripts that listen to it.
list status = [];

// ---- Settings -----------------------------------------------------------
// name, default, lowest, highest. The "Wind Settings" notecard and
// "/8 set name value" override the default; docs/Wind_Settings.txt
// explains each one. Keep all numbers written as floats (1.0, not 1).
list CFG = [
    "speed_gentle",  3.5,  0.5,  40.0,
    "speed_cruise",  8.0,  0.5,  40.0,
    "speed_fast",   16.0,  0.5,  40.0,
    "boost",         1.8,  1.0,   3.0,
    "surface_speed", 0.8,  0.1,   2.0,
    "dive_speed",    0.5,  0.1,   2.0,
    "accel",         0.6,  0.05,  5.0,
    "turn",          0.3,  0.05,  5.0,
    "coast",         1.0,  0.05, 10.0,
    "brake",         0.35, 0.05,  5.0,
    "follow",        0.35, 0.05,  2.0,
    "height_low",    4.0,  1.0, 100.0,
    "height_mid",   15.0,  1.0, 100.0,
    "height_high",  40.0,  1.0, 100.0,
    "height_min",    2.0,  0.5,  20.0,
    "height_max",   80.0, 10.0, 300.0,
    "rise_speed",    4.0,  0.5,  20.0,
    "climb_rate",    6.0,  1.0,  30.0,
    "sink_rate",     2.5,  0.5,  20.0,
    "surface_ride",  0.15, -2.0,  2.0,
    "land_skim",     1.0,  0.3,   5.0,
    "dive_depth",    2.5,  1.0,  30.0,
    "bob",           1.0,  0.0,   3.0,
    "camera",        1.0,  0.0,   1.0,
    "cam_zoom",      1.0,  0.5,   2.0,
    "sound",         1.0,  0.0,   1.0,
    "volume",        0.6,  0.0,   1.0,
    "hud_text",      1.0,  0.0,   1.0,
    "channel",       8.0,  1.0, 99999.0
];

// ---- Helpers ------------------------------------------------------------
// A setting: the stored value if there is one, else the default.
float Cfg(string name) {
    string v = llLinksetDataRead("cfg:" + name);
    if (v != "") return (float)v;
    return llList2Float(CFG, llListFindList(CFG, [name]) + 1);
}

Say(string msg) {
    llOwnerSay("Wind: " + msg);
}

// One field of the last EVT_STATE.
integer Field(integer i) {
    return llList2Integer(status, i);
}

Memory(string who) {
    Say(who + ": " + (string)(llGetUsedMemory() / 1024) + " KB used, " + (string)(llGetFreeMemory() / 1024) + " KB free");
}

integer on = TRUE;         // setting "camera"
float   zoom = 1.0;        // setting "cam_zoom"
integer mine;              // our camera is in use
string  applied;           // the camera we set last

Load() {
    on = (integer)Cfg("camera");
    zoom = Cfg("cam_zoom");
}

Release() {
    applied = "";
    if (mine) if (llGetPermissions() & PERMISSION_CONTROL_CAMERA) llClearCameraParams();
    mine = FALSE;
}

// How far the camera may tilt down behind you and stay under the water.
float DivePitch(float dist) {
    vector p = llList2Vector(llGetObjectDetails(llGetOwner(), [OBJECT_POS]), 0);
    float room = (llWater(ZERO_VECTOR) - 0.5) - (p.z + 0.3);
    float s = room / dist;
    if (s > 0.14) s = 0.14;            // about 8 degrees
    else if (s < -0.42) s = -0.42;     // about -25 degrees
    return (float)llRound(llAsin(s) * RAD_TO_DEG);
}

Apply() {
    if (!Field(S_ACTIVE) || !on) {
        Release();
        return;
    }
    if (!(llGetPermissions() & PERMISSION_CONTROL_CAMERA)) {
        llRequestPermissions(llGetOwner(), PERMISSION_CONTROL_CAMERA);
        return;
    }
    integer lv = Field(S_LEVEL);
    float dist = 5.0;
    float pitch = 10.0;
    vector focus = <2.0, 0.0, 0.5>;
    float lag = 0.35;
    if (lv == L_DIVE) {
        dist = 3.2;
        focus = <1.0, 0.0, 0.3>;
        lag = 0.45;
    } else if (lv == L_SURFACE && Field(S_WATER)) {
        dist = 4.5;
        pitch = 7.0;
        focus = <1.5, 0.0, 0.4>;
        lag = 0.3;
    } else if (lv == L_GLIDE) {
        // 2 m up: close behind; 42 m and more: far back and looking down
        float n = (Field(S_HEIGHT) - 2.0) / 40.0;
        if (n < 0.0) n = 0.0;
        if (n > 1.0) n = 1.0;
        dist = 5.0 + 4.0 * n;
        pitch = 10.0 + 22.0 * n;
    }
    if (Field(S_BOOST)) dist += 1.5;
    dist = dist * zoom;
    if (dist > 10.0) dist = 10.0;
    if (lv == L_DIVE) pitch = DivePitch(dist);
    string now = llDumpList2String([lv, dist, pitch, focus, lag], "|");
    if (now == applied) return;
    applied = now;
    mine = TRUE;
    llSetCameraParams([
        CAMERA_ACTIVE, 1,
        CAMERA_DISTANCE, dist,
        CAMERA_PITCH, pitch,
        CAMERA_FOCUS_OFFSET, focus,
        CAMERA_POSITION_LAG, lag,
        CAMERA_FOCUS_LAG, 0.1,
        CAMERA_BEHINDNESS_ANGLE, 20.0,
        CAMERA_BEHINDNESS_LAG, 0.6,
        CAMERA_POSITION_THRESHOLD, 0.0,
        CAMERA_FOCUS_THRESHOLD, 0.0
    ]);
}

default {
    state_entry() {
        Load();
        // a reset may have left our camera on: take it back and clear it
        if (llGetAttached()) llRequestPermissions(llGetOwner(), PERMISSION_CONTROL_CAMERA);
    }

    on_rez(integer p) {
        llResetScript();
    }

    changed(integer c) {
        if (c & CHANGED_OWNER) llResetScript();
    }

    run_time_permissions(integer perm) {
        if (!(perm & PERMISSION_CONTROL_CAMERA)) return;
        if (Field(S_ACTIVE)) Apply();
        else llClearCameraParams();
    }

    link_message(integer from, integer num, string str, key id) {
        if (num == EVT_STATE) {
            status = llCSV2List(str);
            Apply();
            // under the water, keep checking the depth so the camera stays under too
            if (mine && Field(S_LEVEL) == L_DIVE) llSetTimerEvent(0.5);
            else llSetTimerEvent(0.0);
        }
        else if (num == EVT_SETTINGS) {
            Load();
            applied = "";
            Apply();
        }
        else if (num == MSG_MEMORY) Memory("Camera");
    }

    timer() {
        Apply();
    }
}
