// GENERATED by tools/build.py from src/animator.lsl - edit the source, not this file.
// ---------------------------------------------------------------------
// WIND - ANIMATOR
// Plays your own animations and sounds from the HUD's contents.
//
// Animations (all optional; use any you have, Wind falls back sensibly):
//   Wind Glide     Wind Glide Idle      moving / hovering in the air
//   Wind Surface   Wind Surface Idle    on the water
//   Wind Dive      Wind Dive Idle       under the water
// A missing Idle uses the moving one; a missing level uses Glide; with
// none of these names, the first animation in the HUD plays everywhere;
// with no animation at all, Second Life's own fly / hover.
//
// Sounds (optional, only you hear the loops):
//   Wind Glide Loop, Wind Surface Loop, Wind Dive Loop, Wind Splash
// ---------------------------------------------------------------------
// ---- shared helpers (src/common.lsl): only what this script uses ----
// ---- Levels -------------------------------------------------------------
integer L_GLIDE   = 0;   // above the ground

integer L_SURFACE = 1;   // on the water (just above the land where there is none)

list LEVEL_NAMES = ["Glide", "Surface", "Dive"];

// Engine -> everyone
integer EVT_STATE    = 7100;  // str = the S_* fields joined with ","

// Levels -> everyone
integer EVT_SPLASH   = 7103;  // str = "in" or "out" of the water

// Config <-> everyone
integer EVT_SETTINGS = 7200;  // settings changed: read them again

integer MSG_MEMORY   = 7300;  // everyone: say how much memory you use

// ---- EVT_STATE fields ---------------------------------------------------
integer S_ACTIVE  = 0;  // 1 while Wind is on

integer S_LEVEL   = 1;  // L_*

integer S_MOVING  = 2;  // 1 while travelling

integer S_WATER   = 3;  // Glide/Surface: water is what is below you. Dive: always 1

integer S_SPEED   = 8;  // 0..5, how fast compared with the Fast gear

// The last EVT_STATE, for the scripts that listen to it.
list status = [];

// ---- Settings -----------------------------------------------------------
// name, default, lowest, highest. The "Wind Settings" notecard and
// "/8 set name value" override the default; docs/Wind_Settings.txt
// explains each one. Keep all numbers written as floats (1.0, not 1).
list CFG = [
    "speed_gentle",  3.5,  0.5,  40.0,
    "speed_cruise",  8.0,  0.5,  40.0,
    "speed_fast",   16.0,  0.5,  40.0,
    "boost",         1.8,  1.0,   3.0,
    "surface_speed", 0.8,  0.1,   2.0,
    "dive_speed",    0.5,  0.1,   2.0,
    "accel",         0.6,  0.05,  5.0,
    "turn",          0.3,  0.05,  5.0,
    "coast",         1.0,  0.05, 10.0,
    "brake",         0.35, 0.05,  5.0,
    "follow",        0.35, 0.05,  2.0,
    "height_low",    4.0,  1.0, 100.0,
    "height_mid",   15.0,  1.0, 100.0,
    "height_high",  40.0,  1.0, 100.0,
    "height_min",    2.0,  0.5,  20.0,
    "height_max",   80.0, 10.0, 300.0,
    "rise_speed",    4.0,  0.5,  20.0,
    "climb_rate",    6.0,  1.0,  30.0,
    "sink_rate",     2.5,  0.5,  20.0,
    "surface_ride",  0.15, -2.0,  2.0,
    "land_skim",     1.0,  0.3,   5.0,
    "dive_depth",    2.5,  1.0,  30.0,
    "bob",           1.0,  0.0,   3.0,
    "camera",        1.0,  0.0,   1.0,
    "cam_zoom",      1.0,  0.5,   2.0,
    "sound",         1.0,  0.0,   1.0,
    "volume",        0.6,  0.0,   1.0,
    "hud_text",      1.0,  0.0,   1.0,
    "channel",       8.0,  1.0, 99999.0
];

// ---- Helpers ------------------------------------------------------------
// A setting: the stored value if there is one, else the default.
float Cfg(string name) {
    string v = llLinksetDataRead("cfg:" + name);
    if (v != "") return (float)v;
    return llList2Float(CFG, llListFindList(CFG, [name]) + 1);
}

Say(string msg) {
    llOwnerSay("Wind: " + msg);
}

// One field of the last EVT_STATE.
integer Field(integer i) {
    return llList2Integer(status, i);
}

Memory(string who) {
    Say(who + ": " + (string)(llGetUsedMemory() / 1024) + " KB used, " + (string)(llGetFreeMemory() / 1024) + " KB free");
}

string  playing;           // our animation running now
string  avatar_state;      // the avatar's own animation state when we last looked
string  loop;              // our looping sound now
float   loop_vol;
integer sound_on = TRUE;
float   volume = 0.6;

Load() {
    sound_on = (integer)Cfg("sound");
    volume = Cfg("volume");
}

// The level whose animations and sounds fit: on the Surface level over
// land you hover like gliding.
integer Look() {
    integer lv = Field(S_LEVEL);
    if (lv == L_SURFACE && !Field(S_WATER)) lv = L_GLIDE;
    return lv;
}

string Pick() {
    string base = "Wind " + llList2String(LEVEL_NAMES, Look());
    list names = [base, "Wind Glide"];
    if (!Field(S_MOVING)) names = [base + " Idle", base, "Wind Glide Idle", "Wind Glide"];
    integer i;
    for (i = 0; i < llGetListLength(names); ++i) {
        string n = llList2String(names, i);
        if (llGetInventoryType(n) == INVENTORY_ANIMATION) return n;
    }
    if (llGetInventoryNumber(INVENTORY_ANIMATION) > 0) return llGetInventoryName(INVENTORY_ANIMATION, 0);
    if (Field(S_MOVING)) return "fly";
    return "hover";
}

Animate() {
    string want = "";
    if (Field(S_ACTIVE)) want = Pick();
    if (want == playing) return;
    if (!(llGetPermissions() & PERMISSION_TRIGGER_ANIMATION)) {
        if (want != "") llRequestPermissions(llGetOwner(), PERMISSION_TRIGGER_ANIMATION);
        return;
    }
    // start the new one before stopping the old, so there is no gap
    if (want != "") llStartAnimation(want);
    if (playing != "") llStopAnimation(playing);
    playing = want;
}

Sound() {
    string want = "";
    if (Field(S_ACTIVE) && sound_on) {
        string n = "Wind " + llList2String(LEVEL_NAMES, Look()) + " Loop";
        if (llGetInventoryType(n) == INVENTORY_SOUND) want = n;
    }
    // louder the faster you go
    float v = volume * (0.4 + 0.12 * Field(S_SPEED));
    if (want != loop) {
        if (want == "") llStopSound();
        else llLoopSound(want, v);
        loop = want;
        loop_vol = v;
    } else if (want != "") if (llFabs(v - loop_vol) > 0.05) {
        llAdjustSoundVolume(v);
        loop_vol = v;
    }
}

default {
    state_entry() {
        Load();
        llStopSound();
    }

    on_rez(integer p) {
        llResetScript();
    }

    attach(key id) {
        // taken off while on: a looped animation would keep playing without us
        if (id == NULL_KEY) if (playing != "") if (llGetPermissions() & PERMISSION_TRIGGER_ANIMATION) llStopAnimation(playing);
    }

    changed(integer c) {
        if (c & CHANGED_OWNER) llResetScript();
        if (c & CHANGED_INVENTORY) {
            // animations or sounds were added or removed: choose again
            if (playing != "") if (llGetPermissions() & PERMISSION_TRIGGER_ANIMATION) llStopAnimation(playing);
            playing = "";
            loop = "";
            Animate();
            Sound();
        }
    }

    run_time_permissions(integer perm) {
        if (perm & PERMISSION_TRIGGER_ANIMATION) Animate();
    }

    link_message(integer from, integer num, string str, key id) {
        if (num == EVT_STATE) {
            status = llCSV2List(str);
            Animate();
            Sound();
            // while on, look now and then whether the avatar's own animation
            // (or an AO) took over, and if so play ours again on top
            if (Field(S_ACTIVE)) llSetTimerEvent(1.0);
            else llSetTimerEvent(0.0);
        }
        else if (num == EVT_SPLASH) {
            if (sound_on) if (llGetInventoryType("Wind Splash") == INVENTORY_SOUND) llTriggerSound("Wind Splash", volume);
        }
        else if (num == EVT_SETTINGS) {
            Load();
            Sound();
        }
        else if (num == MSG_MEMORY) Memory("Animator");
    }

    timer() {
        string s = llGetAnimation(llGetOwner());
        if (s == avatar_state) return;
        avatar_state = s;
        if (playing != "") if (llGetPermissions() & PERMISSION_TRIGGER_ANIMATION) {
            llStopAnimation(playing);
            llStartAnimation(playing);
        }
    }
}
