// GENERATED by tools/build.py from src/hud.lsl - edit the source, not this file.
// ---------------------------------------------------------------------
// WIND - HUD
// Touching the HUD, the menu, the status text above the HUD and the chat
// commands (/8 unless the settings say otherwise). It only asks; the
// Engine decides and tells everyone what happened (EVT_STATE), and that
// is what the text and the button glow show.
//
// Buttons are found by prim name (upper or lower case):
//   glide, surface, dive        go to that level (starts Wind if it is off)
//   up, down, low, mid, high    glide height
//   speed                       next speed: Gentle, Cruise, Fast
//   menu                        the menu
//   help                        the user manual
//   power, or any other name    start / land
// Holding any button for a moment opens the menu. A HUD of one single
// prim works too: tap to start and land, hold for the menu.
// ---------------------------------------------------------------------
// ---- shared helpers (src/common.lsl): only what this script uses ----
// ---------------------------------------------------------------------
// Shared definitions. tools/build.py copies into each Wind script only
// the parts that script uses (Second Life counts code against each
// script's memory). Edit here, then rebuild. Never edit a built script.
//
// Rules for this file, so the build tool can read it:
//   - a global variable is ONE line:  type NAME = value;
//     except a list, which may start with "list NAME = [" on its own
//     line and end with a line ending in "];"
//   - a function starts at column 0 and ends with a lone "}" at column 0.
// ---------------------------------------------------------------------
string VERSION = "0.1.0";

string MANUAL_NOTECARD = "Wind - User Manual";

// ---- Levels -------------------------------------------------------------
integer L_GLIDE   = 0;   // above the ground

integer L_DIVE    = 2;   // under the water

list LEVEL_NAMES = ["Glide", "Surface", "Dive"];

list GEAR_NAMES  = ["Gentle", "Cruise", "Fast"];

// ---- Link messages ------------------------------------------------------
// HUD -> Engine and Levels
integer CMD_START    = 7001;  // str = level number, "" = automatic

integer CMD_STOP     = 7002;  // land gently, then switch off (twice = at once)

integer CMD_HALT     = 7003;  // switch off right now (Levels sends it when landed)

integer CMD_LEVEL    = 7004;  // str = level number (starts Wind if it is off)

integer CMD_HEIGHT   = 7005;  // str = "low" "mid" "high" "up" "down" (starts Wind in Glide if off)

integer CMD_GEAR     = 7006;  // str = gear number, or "next"

integer CMD_DEBUG    = 7007;  // str = "1" live numbers on, "0" off

// Engine -> everyone
integer EVT_STATE    = 7100;  // str = the S_* fields joined with ","

// EVT_DEBUG: the Engine's live numbers, comma separated:
// speed, guide speed, guide distance, blocked (1/0)
integer EVT_DEBUG    = 7101;

// EVT_DEBUG_LEVELS: the Levels script's live numbers, comma separated:
// level, feet above what is below, water below (1/0), depth,
// feet above the bottom, wall distance (0 = none)
integer EVT_DEBUG_LEVELS = 7102;

// Config <-> everyone
integer EVT_SETTINGS = 7200;  // settings changed: read them again

integer SET_COMMAND  = 7201;  // HUD -> Config: str = "set name value", "get name", "settings", "reload", "defaults"

integer MSG_MEMORY   = 7300;  // everyone: say how much memory you use

// ---- EVT_STATE fields ---------------------------------------------------
integer S_ACTIVE  = 0;  // 1 while Wind is on

integer S_LEVEL   = 1;  // L_*

integer S_HEIGHT  = 4;  // Glide height setting, whole metres

integer S_GEAR    = 5;  // 0 Gentle, 1 Cruise, 2 Fast

integer S_BOOST   = 6;  // 1 while boosting (double-tap W and hold)

integer S_LANDING = 7;  // 1 while landing

// The last EVT_STATE, for the scripts that listen to it.
list status = [];

// ---- Settings -----------------------------------------------------------
// name, default, lowest, highest. The "Wind Settings" notecard and
// "/8 set name value" override the default; docs/Wind_Settings.txt
// explains each one. Keep all numbers written as floats (1.0, not 1).
list CFG = [
    "speed_gentle",  3.5,  0.5,  40.0,
    "speed_cruise",  8.0,  0.5,  40.0,
    "speed_fast",   16.0,  0.5,  40.0,
    "boost",         1.8,  1.0,   3.0,
    "surface_speed", 0.8,  0.1,   2.0,
    "dive_speed",    0.5,  0.1,   2.0,
    "accel",         0.6,  0.05,  5.0,
    "turn",          0.3,  0.05,  5.0,
    "coast",         1.0,  0.05, 10.0,
    "brake",         0.35, 0.05,  5.0,
    "follow",        0.35, 0.05,  2.0,
    "height_low",    4.0,  1.0, 100.0,
    "height_mid",   15.0,  1.0, 100.0,
    "height_high",  40.0,  1.0, 100.0,
    "height_min",    2.0,  0.5,  20.0,
    "height_max",   80.0, 10.0, 300.0,
    "rise_speed",    4.0,  0.5,  20.0,
    "climb_rate",    6.0,  1.0,  30.0,
    "sink_rate",     2.5,  0.5,  20.0,
    "surface_ride",  0.15, -2.0,  2.0,
    "land_skim",     1.0,  0.3,   5.0,
    "dive_depth",    2.5,  1.0,  30.0,
    "bob",           1.0,  0.0,   3.0,
    "camera",        1.0,  0.0,   1.0,
    "cam_zoom",      1.0,  0.5,   2.0,
    "sound",         1.0,  0.0,   1.0,
    "volume",        0.6,  0.0,   1.0,
    "hud_text",      1.0,  0.0,   1.0,
    "channel",       8.0,  1.0, 99999.0
];

// ---- Helpers ------------------------------------------------------------
// A setting: the stored value if there is one, else the default.
float Cfg(string name) {
    string v = llLinksetDataRead("cfg:" + name);
    if (v != "") return (float)v;
    return llList2Float(CFG, llListFindList(CFG, [name]) + 1);
}

Send(integer num, string str) {
    llMessageLinked(LINK_SET, num, str, "");
}

Say(string msg) {
    llOwnerSay("Wind: " + msg);
}

// One field of the last EVT_STATE.
integer Field(integer i) {
    return llList2Integer(status, i);
}

// A number with up to two decimals: 8, 0.5, 0.15, -1.25
string Fmt(float x) {
    integer i = llRound(x * 100.0);
    string s = "";
    if (i < 0) {
        s = "-";
        i = -i;
    }
    s += (string)(i / 100);
    integer d = i % 100;
    if (d) {
        s += "." + (string)(d / 10);
        if (d % 10) s += (string)(d % 10);
    }
    return s;
}

Memory(string who) {
    Say(who + ": " + (string)(llGetUsedMemory() / 1024) + " KB used, " + (string)(llGetFreeMemory() / 1024) + " KB free");
}

integer chan;              // chat command channel
integer chat_h;
integer menu_chan;
integer menu_h;
float   menu_t;            // when the menu was opened (its listener expires)
integer reopen;            // after a choice, show again: 1 the menu, 2 the options
float   touch_t;
integer touch_link;
integer text_on = TRUE;
integer cam_on = TRUE;
integer snd_on = TRUE;
integer debug;
string  dbg_levels;        // the latest live numbers (see Numbers)
string  dbg_engine;
string  shown;             // the text above the HUD now
string  lit;               // which buttons glow now
integer greeted;           // welcome checked since the last reset
list    glows;             // stride 2: link number, what it lights up for

Load() {
    text_on = (integer)Cfg("hud_text");
    cam_on = (integer)Cfg("camera");
    snd_on = (integer)Cfg("sound");
    integer c = (integer)Cfg("channel");
    if (c != chan || !chat_h) {
        chan = c;
        llListenRemove(chat_h);
        chat_h = llListen(chan, "", llGetOwner(), "");
    }
}

FindButtons() {
    glows = [];
    lit = "";
    integer n = llGetNumberOfPrims();
    if (n < 2) return;
    integer i;
    for (i = 1; i <= n; ++i) {
        string name = llToLower(llStringTrim(llGetLinkName(i), STRING_TRIM));
        if (llListFindList(["power", "glide", "surface", "dive"], [name]) != -1) glows += [i, name];
    }
}

// The power button glows while Wind is on, and the level you are in.
Highlight() {
    string now = (string)Field(S_ACTIVE) + (string)Field(S_LEVEL);
    if (now == lit) return;
    lit = now;
    integer i;
    for (i = 0; i < llGetListLength(glows); i += 2) {
        string what = llList2String(glows, i + 1);
        float g;
        if (Field(S_ACTIVE)) {
            if (what == "power") g = 0.1;
            else if (what == llToLower(llList2String(LEVEL_NAMES, Field(S_LEVEL)))) g = 0.2;
        }
        llSetLinkPrimitiveParamsFast(llList2Integer(glows, i), [PRIM_GLOW, ALL_SIDES, g]);
    }
}

ShowText() {
    string t = "";
    vector col = <0.8, 0.95, 1.0>;
    if (debug && Field(S_ACTIVE) && dbg_levels != "") {
        t = Numbers();
        col = <1.0, 0.9, 0.5>;
    } else if (text_on && Field(S_ACTIVE)) {
        integer lv = Field(S_LEVEL);
        t = llToUpper(llList2String(LEVEL_NAMES, lv));
        if (lv == L_GLIDE) t += "  " + (string)Field(S_HEIGHT) + " m";
        t += "  ·  " + llList2String(GEAR_NAMES, Field(S_GEAR));
        if (Field(S_BOOST)) t += "  ·  BOOST";
        if (Field(S_LANDING)) t = "landing...";
    }
    if (t == shown) return;
    shown = t;
    llSetText(t, col, 1.0);
}

// The live numbers from the Levels script (EVT_DEBUG_LEVELS) and the
// Engine (EVT_DEBUG), in words.
string Numbers() {
    list d = llCSV2List(dbg_levels);
    list e = llCSV2List(dbg_engine);
    integer lv = llList2Integer(d, 0);
    string t = llList2String(LEVEL_NAMES, lv) + ": feet " + Fmt(llList2Float(d, 1)) + " m above the ";
    if (llList2Integer(d, 2)) t += "water";
    else t += "ground";
    if (lv == L_DIVE) t = "Dive: " + Fmt(llList2Float(d, 3)) + " m deep, " + Fmt(llList2Float(d, 4)) + " m above the bottom";
    if (llList2Float(d, 5) > 0.0) t += ", wall " + Fmt(llList2Float(d, 5)) + " m";
    t += "\nspeed " + Fmt(llList2Float(e, 0)) + " of " + Fmt(llList2Float(e, 1)) + " m/s, guide " + Fmt(llList2Float(e, 2)) + " m ahead";
    if (llList2Integer(e, 3)) t += ", BLOCKED";
    return t;
}

string Line() {
    string gear = llList2String(GEAR_NAMES, Field(S_GEAR));
    if (!Field(S_ACTIVE)) return "Off.  Speed: " + gear + ".";
    string t = llList2String(LEVEL_NAMES, Field(S_LEVEL));
    if (Field(S_LEVEL) == L_GLIDE) t += " at " + (string)Field(S_HEIGHT) + " m";
    return "Now: " + t + ",  " + gear + ".";
}

string OnOff(string name, integer on) {
    if (on) return name + ": on";
    return name + ": off";
}

Dialog(string text, list buttons) {
    llListenRemove(menu_h);
    menu_chan = -1 - (integer)llFrand(2000000000.0);
    menu_h = llListen(menu_chan, "", llGetOwner(), "");
    llDialog(llGetOwner(), text, buttons, menu_chan);
    menu_t = llGetTime();
    llSetTimerEvent(5.0);
}

Menu() {
    string go = "Start";
    if (Field(S_ACTIVE)) go = "Land";
    Dialog("Wind " + VERSION + "\n" + Line() + "\n\nGlide: through the air.  Surface: on the water.  Dive: under it.\nLow / Mid / High: how high you glide.\nGentle / Cruise / Fast: how fast you go.",
        [go, "Options", "Close", "Gentle", "Cruise", "Fast", "Low", "Mid", "High", "Glide", "Surface", "Dive"]);
}

Options() {
    Dialog("Wind options\n\nCamera: Wind moves your camera (off: your own camera).\nSound: Wind's sounds, if the HUD has any.\nText: the line above the HUD.\nNumbers: live height and speed, for testing.\nReload: read the settings notecard again.",
        ["Back", "Close", "Help", OnOff("Camera", cam_on), OnOff("Sound", snd_on), OnOff("Text", text_on), OnOff("Numbers", debug), "Memory", "Reload"]);
}

Help() {
    if (llGetInventoryType(MANUAL_NOTECARD) == INVENTORY_NOTECARD) llGiveInventory(llGetOwner(), MANUAL_NOTECARD);
    string c = "/" + (string)chan + " ";
    Say("Tap the HUD to rise, tap again to land. Hold the HUD for the menu.\n"
        + "W / S: forward and back.  A / D: turn.  Double-tap W and hold it: boost.\n"
        + "E / C: up and down. Keep holding C at the lowest glide to settle on the water (over land: to land). On the water, tap C to dive and E to rise again.\n"
        + "Chat: " + c + "glide, surface, dive, low, mid, high, gentle, cruise, fast, land, menu, numbers. Settings: " + c + "set name value, " + c + "settings, " + c + "reload.");
}

SetDebug(integer on) {
    debug = on;
    dbg_levels = "";
    dbg_engine = "";
    Send(CMD_DEBUG, (string)on);
    ShowText();
}

// A chat command, or a menu button (same words).
Command(string m) {
    list w = llParseString2List(llToLower(llStringTrim(m, STRING_TRIM)), [" "], []);
    string c = llList2String(w, 0);
    integer i = llListFindList(["glide", "surface", "dive"], [c]);
    if (i != -1) Send(CMD_LEVEL, (string)i);
    else if ((i = llListFindList(["gentle", "cruise", "fast"], [c])) != -1) Send(CMD_GEAR, (string)i);
    else if (llListFindList(["low", "mid", "high", "up", "down"], [c]) != -1) Send(CMD_HEIGHT, c);
    else if (c == "speed") Send(CMD_GEAR, "next");
    else if (c == "on" || c == "start") Send(CMD_START, "");
    else if (c == "off" || c == "land" || c == "stop") Send(CMD_STOP, "");
    else if (c == "halt") Send(CMD_HALT, "");
    else if (c == "menu") Menu();
    else if (c == "numbers" || c == "debug") SetDebug(!debug);
    else if (c == "memory") Send(MSG_MEMORY, "");
    else if (c == "help") Help();
    else if (llListFindList(["set", "get", "settings", "reload", "defaults"], [c]) != -1) Send(SET_COMMAND, llDumpList2String(w, " "));
    else Say("I do not know \"" + m + "\". Type /" + (string)chan + " help");
}

Choice(string m) {
    llListenRemove(menu_h);
    menu_h = 0;
    string w = llToLower(llStringTrim(llList2String(llParseString2List(m, [":"], []), 0), STRING_TRIM));
    if (w == "close") return;
    if (w == "options") Options();
    else if (w == "back") Menu();
    else if (w == "help" || w == "memory") Command(w);
    else if (w == "start" || w == "land") Command(w);
    else if (w == "camera" || w == "sound" || w == "text") {
        if (w == "text") w = "hud_text";
        Send(SET_COMMAND, "set " + w + " " + (string)(!(integer)Cfg(w)));
        reopen = 2;
    } else if (w == "numbers") {
        SetDebug(!debug);
        reopen = 2;
    } else if (w == "reload") Send(SET_COMMAND, "reload");
    else {
        Command(w);
        reopen = 1;
    }
    // show the menu again once the change has gone round
    if (reopen) llSetTimerEvent(0.4);
}

default {
    state_entry() {
        FindButtons();
        Load();
        ShowText();
    }

    on_rez(integer p) {
        llResetScript();
    }

    changed(integer c) {
        if (c & CHANGED_OWNER) llResetScript();
        if (c & CHANGED_LINK) FindButtons();
    }

    touch_start(integer n) {
        if (llDetectedKey(0) != llGetOwner()) return;
        touch_t = llGetTime();
        touch_link = llDetectedLinkNumber(0);
    }

    touch_end(integer n) {
        if (llDetectedKey(0) != llGetOwner()) return;
        if (llGetTime() - touch_t > 0.8) {
            Menu();
            return;
        }
        string name = llToLower(llStringTrim(llGetLinkName(touch_link), STRING_TRIM));
        integer i = llListFindList(["glide", "surface", "dive"], [name]);
        if (i != -1) Send(CMD_LEVEL, (string)i);
        else if (llListFindList(["up", "down", "low", "mid", "high"], [name]) != -1) Send(CMD_HEIGHT, name);
        else if (name == "speed") Send(CMD_GEAR, "next");
        else if (name == "menu") Menu();
        else if (name == "help") Help();
        else if (Field(S_ACTIVE)) Send(CMD_STOP, "");
        else Send(CMD_START, "");
    }

    listen(integer ch, string name, key id, string msg) {
        if (ch == menu_chan) Choice(msg);
        else Command(msg);
    }

    link_message(integer from, integer num, string str, key id) {
        if (num == EVT_STATE) {
            status = llCSV2List(str);
            ShowText();
            Highlight();
        }
        else if (num == EVT_DEBUG) {
            dbg_engine = str;
            if (debug) ShowText();
        }
        else if (num == EVT_DEBUG_LEVELS) {
            dbg_levels = str;
            if (debug) ShowText();
        }
        else if (num == EVT_SETTINGS) {
            Load();
            ShowText();
            if (!greeted) {
                // the first settings message after a reset: welcome a new owner once
                greeted = TRUE;
                if (llLinksetDataRead("st:welcomed") != (string)llGetOwner()) {
                    llLinksetDataWrite("st:welcomed", (string)llGetOwner());
                    Say("Welcome to Wind " + VERSION + "! Tap the HUD to rise into the air and explore. W to go, A / D to turn, E / C for up and down. Hold the HUD for the menu, or type /" + (string)chan + " help.");
                }
            }
        }
        else if (num == MSG_MEMORY) Memory("HUD");
    }

    timer() {
        if (reopen) {
            integer r = reopen;
            reopen = 0;
            if (r == 2) Options();
            else Menu();
            return;
        }
        if (menu_h) if (llGetTime() - menu_t > 120.0) {
            llListenRemove(menu_h);
            menu_h = 0;
        }
        if (!menu_h) llSetTimerEvent(0.0);
    }
}
