// GENERATED by tools/build.py from src/config.lsl - edit the source, not this file.
// ---------------------------------------------------------------------
// WIND - CONFIG
// Reads the "Wind Settings" notecard into the HUD's own memory
// (LinksetData, keys "cfg:<name>"), where the other scripts read it with
// Cfg(). Also answers /8 set, get, settings, reload and defaults.
// Only this script writes settings.
//
// The notecard is read when the HUD first starts for a new owner, when
// the notecard is saved (edited), and on /8 reload. Values from
// "/8 set" last until the notecard is read again.
// ---------------------------------------------------------------------
// ---- shared helpers (src/common.lsl): only what this script uses ----
string SETTINGS_NOTECARD = "Wind Settings";

// Config <-> everyone
integer EVT_SETTINGS = 7200;  // settings changed: read them again

integer SET_COMMAND  = 7201;  // HUD -> Config: str = "set name value", "get name", "settings", "reload", "defaults"

integer MSG_MEMORY   = 7300;  // everyone: say how much memory you use

// ---- Settings -----------------------------------------------------------
// name, default, lowest, highest. The "Wind Settings" notecard and
// "/8 set name value" override the default; docs/Wind_Settings.txt
// explains each one. Keep all numbers written as floats (1.0, not 1).
list CFG = [
    "speed_gentle",  3.5,  0.5,  40.0,
    "speed_cruise",  8.0,  0.5,  40.0,
    "speed_fast",   16.0,  0.5,  40.0,
    "boost",         1.8,  1.0,   3.0,
    "surface_speed", 0.8,  0.1,   2.0,
    "dive_speed",    0.5,  0.1,   2.0,
    "accel",         0.6,  0.05,  5.0,
    "turn",          0.3,  0.05,  5.0,
    "coast",         1.0,  0.05, 10.0,
    "brake",         0.35, 0.05,  5.0,
    "follow",        0.35, 0.05,  2.0,
    "height_low",    4.0,  1.0, 100.0,
    "height_mid",   15.0,  1.0, 100.0,
    "height_high",  40.0,  1.0, 100.0,
    "height_min",    2.0,  0.5,  20.0,
    "height_max",   80.0, 10.0, 300.0,
    "rise_speed",    4.0,  0.5,  20.0,
    "climb_rate",    6.0,  1.0,  30.0,
    "sink_rate",     2.5,  0.5,  20.0,
    "surface_ride",  0.15, -2.0,  2.0,
    "land_skim",     1.0,  0.3,   5.0,
    "dive_depth",    2.5,  1.0,  30.0,
    "bob",           1.0,  0.0,   3.0,
    "camera",        1.0,  0.0,   1.0,
    "cam_zoom",      1.0,  0.5,   2.0,
    "sound",         1.0,  0.0,   1.0,
    "volume",        0.6,  0.0,   1.0,
    "hud_text",      1.0,  0.0,   1.0,
    "channel",       8.0,  1.0, 99999.0
];

// ---- Helpers ------------------------------------------------------------
// A setting: the stored value if there is one, else the default.
float Cfg(string name) {
    string v = llLinksetDataRead("cfg:" + name);
    if (v != "") return (float)v;
    return llList2Float(CFG, llListFindList(CFG, [name]) + 1);
}

Send(integer num, string str) {
    llMessageLinked(LINK_SET, num, str, "");
}

Say(string msg) {
    llOwnerSay("Wind: " + msg);
}

// A number with up to two decimals: 8, 0.5, 0.15, -1.25
string Fmt(float x) {
    integer i = llRound(x * 100.0);
    string s = "";
    if (i < 0) {
        s = "-";
        i = -i;
    }
    s += (string)(i / 100);
    integer d = i % 100;
    if (d) {
        s += "." + (string)(d / 10);
        if (d % 10) s += (string)(d % 10);
    }
    return s;
}

Memory(string who) {
    Say(who + ": " + (string)(llGetUsedMemory() / 1024) + " KB used, " + (string)(llGetFreeMemory() / 1024) + " KB free");
}

key     query;
integer line;
integer good;
integer bad;
integer tell;              // say when done (a reload you asked for)

// The notecard as it is now, to notice edits ("none" if there is none).
string CardId() {
    if (llGetInventoryType(SETTINGS_NOTECARD) != INVENTORY_NOTECARD) return "none";
    return (string)llGetInventoryKey(SETTINGS_NOTECARD);
}

Load(integer say) {
    llLinksetDataDeleteFound("^cfg:", "");
    tell = say;
    good = 0;
    bad = 0;
    line = 0;
    llLinksetDataWrite("st:card", CardId());
    if (llGetInventoryType(SETTINGS_NOTECARD) != INVENTORY_NOTECARD) {
        Done();
        return;
    }
    query = llGetNotecardLine(SETTINGS_NOTECARD, line);
}

Done() {
    query = NULL_KEY;
    Send(EVT_SETTINGS, "");
    if (tell || bad) {
        string m = "Settings: " + (string)good + " read from the notecard";
        if (bad) m += ", " + (string)bad + " line(s) skipped";
        Say(m + ".");
    }
}

integer Number(string s) {
    string c = llGetSubString(s, 0, 0);
    if (c == "-" || c == "+") {
        s = llDeleteSubString(s, 0, 0);
        c = llGetSubString(s, 0, 0);
    }
    if (c == ".") c = llGetSubString(s, 1, 1);
    if (c == "") return FALSE;
    return llSubStringIndex("0123456789", c) != -1;
}

// Checks and stores one setting. Returns "" or what is wrong.
string Store(string name, string value) {
    name = llToLower(name);
    integer i = llListFindList(CFG, [name]);
    if (i == -1) return "there is no setting called \"" + name + "\"";
    string v = llToLower(value);
    float f;
    if (v == "on" || v == "yes" || v == "true") f = 1.0;
    else if (v == "off" || v == "no" || v == "false") f = 0.0;
    else if (Number(v)) f = (float)v;
    else return name + ": \"" + value + "\" is not a number";
    float lo = llList2Float(CFG, i + 2);
    float hi = llList2Float(CFG, i + 3);
    if (f < lo || f > hi) return name + " must be from " + Fmt(lo) + " to " + Fmt(hi);
    llLinksetDataWrite("cfg:" + name, (string)f);
    return "";
}

// One notecard line: "name = value", with # starting a comment.
Line(string s) {
    integer c = llSubStringIndex(s, "#");
    if (c == 0) return;
    if (c > 0) s = llGetSubString(s, 0, c - 1);
    s = llStringTrim(s, STRING_TRIM);
    if (s == "") return;
    integer eq = llSubStringIndex(s, "=");
    string err = "it should look like: name = value";
    if (eq > 0) {
        string value = "";
        if (eq < llStringLength(s) - 1) value = llStringTrim(llGetSubString(s, eq + 1, -1), STRING_TRIM);
        err = Store(llStringTrim(llGetSubString(s, 0, eq - 1), STRING_TRIM), value);
    }
    if (err == "") ++good;
    else {
        ++bad;
        Say(SETTINGS_NOTECARD + " line " + (string)(line + 1) + ": " + err + " (skipped)");
    }
}

ListAll() {
    string out = "settings:";
    integer i;
    for (i = 0; i < llGetListLength(CFG); i += 4) {
        string name = llList2String(CFG, i);
        string one = "  " + name + " " + Fmt(Cfg(name));
        if (llLinksetDataRead("cfg:" + name) == "") one += "*";
        if (llStringLength(out + one) > 900) {
            Say(out);
            out = "";
        }
        out += one;
    }
    Say(out + "\n(* = default)");
}

Command(string m) {
    list w = llParseString2List(m, [" "], []);
    string c = llList2String(w, 0);
    string name = llToLower(llList2String(w, 1));
    if (c == "set") {
        if (llGetListLength(w) < 3) {
            Say("Use: set name value.  For example: set speed_cruise 7");
            return;
        }
        string err = Store(name, llList2String(w, 2));
        if (err != "") {
            Say(err);
            return;
        }
        Say(name + " = " + Fmt(Cfg(name)) + "  (until the settings notecard is read again)");
        Send(EVT_SETTINGS, "");
    }
    else if (c == "get") {
        if (llListFindList(CFG, [name]) == -1) Say("there is no setting called \"" + name + "\"");
        else Say(name + " = " + Fmt(Cfg(name)));
    }
    else if (c == "settings") ListAll();
    else if (c == "reload") Load(TRUE);
    else if (c == "defaults") {
        llLinksetDataDeleteFound("^cfg:", "");
        Send(EVT_SETTINGS, "");
        Say("All settings are back to their defaults. Reload reads the notecard again.");
    }
}

default {
    state_entry() {
        string me = (string)llGetOwner();
        if (llLinksetDataRead("st:owner") != me) {
            // a new owner, or the very first start: nothing from before is kept
            llLinksetDataReset();
            llLinksetDataWrite("st:owner", me);
            Load(FALSE);
        }
        else if (llLinksetDataRead("st:card") != CardId()) Load(FALSE);
        else Done();
    }

    on_rez(integer p) {
        llResetScript();
    }

    changed(integer c) {
        if (c & CHANGED_OWNER) llResetScript();
        if (c & CHANGED_INVENTORY) {
            // read the notecard again if it was edited, added or removed
            string id = CardId();
            if (id != llLinksetDataRead("st:card") || id == (string)NULL_KEY) Load(TRUE);
        }
    }

    dataserver(key id, string data) {
        if (id != query) return;
        if (data == EOF) {
            Done();
            return;
        }
        Line(data);
        ++line;
        query = llGetNotecardLine(SETTINGS_NOTECARD, line);
    }

    link_message(integer from, integer num, string str, key id) {
        if (num == SET_COMMAND) Command(str);
        else if (num == MSG_MEMORY) Memory("Config");
    }
}
