#!/usr/bin/env python3
"""Builds the scripts you paste into Second Life.

Every script in src/ has the line `// @include common`. It is replaced by the
parts of src/common.lsl that the script actually uses (directly, or through
other shared parts). Second Life counts compiled code against each script's
64 KB, so unused helpers must not be pasted in.

    python3 tools/build.py            build, and print the size of each script
    python3 tools/build.py --check    also run a strict LSL syntax/type check

The checker is not part of this repo. Point LSLOPT at a checkout of
https://github.com/Sei-Lisa/LSL-PyOptimizer (default: /tmp/lslopt).

Besides building, it refuses to build when:
  - a string uses a backslash code LSL does not have (only \\n \\" \\\\ work),
  - a script asks for a setting (Cfg("name")) that is not in the CFG table,
  - docs/Wind_Settings.txt (the settings notecard) and the CFG table disagree.
"""
import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SRC = os.path.join(ROOT, "src")
SETTINGS_DOC = os.path.join(ROOT, "docs", "Wind_Settings.txt")
LSLOPT = os.environ.get("LSLOPT", "/tmp/lslopt")

# Source file -> name of the script inside the HUD (also the output file name).
SCRIPTS = {
    "engine.lsl": "Wind Engine.lsl",
    "levels.lsl": "Wind Levels.lsl",
    "camera.lsl": "Wind Camera.lsl",
    "animator.lsl": "Wind Animator.lsl",
    "hud.lsl": "Wind HUD.lsl",
    "config.lsl": "Wind Config.lsl",
}

# Rough size guide, in LSL tokens. Scripts above this get a warning.
# Measured in-world on Sentinel: 3,788 tokens started fine, 5,373 crashed.
TOKEN_WARN = 3800

BANNER = "// GENERATED by tools/build.py from src/{src} - edit the source, not this file.\n"

TYPES = r"(?:string|integer|float|vector|list|key|rotation)"
VAR_RE = re.compile(r"^" + TYPES + r"\s+(\w+)\s*=.*;\s*(?://.*)?$")
LIST_START_RE = re.compile(r"^list\s+(\w+)\s*=\s*\[\s*(?://.*)?$")
FUN_RE = re.compile(r"^(?:" + TYPES + r"\s+)?(\w+)\s*\([^)]*\)\s*\{\s*$")
# strings and comments are matched first so "http://..." is not read as a comment
TOKEN_RE = re.compile(r'("(?:[^"\\\n]|\\.)*")|(//[^\n]*)|([A-Za-z_]\w*|\d[\w.]*|<<|>>|==|!=|<=|>=|&&|\|\||\+\+|--|[-+*/%<>=!&|^~(){}\[\];,.@])')
CFG_USE_RE = re.compile(r'\bCfg\(\s*"([^"]*)"\s*\)')


def identifiers(text):
    return {m.group(3) for m in TOKEN_RE.finditer(text) if m.group(3)}


def token_count(text):
    return sum(1 for m in TOKEN_RE.finditer(text) if m.group(1) or m.group(3))


def parse_common(text):
    """Splits common.lsl into [(name, text)] items: globals and functions."""
    items = []
    pending = []
    lines = text.split("\n")
    i = 0
    while i < len(lines):
        line = lines[i]
        if line.strip() == "":
            i += 1
        elif line.startswith("//"):
            pending.append(line)
            i += 1
        elif VAR_RE.match(line):
            items.append((VAR_RE.match(line).group(1), "\n".join(pending + [line])))
            pending = []
            i += 1
        elif LIST_START_RE.match(line):
            name = LIST_START_RE.match(line).group(1)
            body = [line]
            i += 1
            while i < len(lines) and not lines[i].rstrip().endswith("];"):
                body.append(lines[i])
                i += 1
            if i == len(lines):
                sys.exit("common.lsl: list %s never ends (a line ending in '];')" % name)
            body.append(lines[i])
            i += 1
            items.append((name, "\n".join(pending + body)))
            pending = []
        elif FUN_RE.match(line):
            name = FUN_RE.match(line).group(1)
            body = [line]
            i += 1
            while i < len(lines) and lines[i] != "}":
                body.append(lines[i])
                i += 1
            body.append("}")
            i += 1
            items.append((name, "\n".join(pending + body)))
            pending = []
        else:
            sys.exit("common.lsl: cannot parse line: " + line)
    return items


def shake(items, script_text):
    """Returns the common items the script needs, in their original order."""
    by_name = {name: text for name, text in items}
    need = set()
    todo = [n for n in identifiers(script_text) if n in by_name]
    while todo:
        n = todo.pop()
        if n in need:
            continue
        need.add(n)
        todo.extend(m for m in identifiers(by_name[n]) if m in by_name and m != n)
    return [text for name, text in items if name in need]


def lint_escapes(name, text):
    """LSL string literals only understand \\n, \\t (four spaces), \\" and \\\\.
    Anything else silently becomes the plain letter ("\\r" is the letter r), so refuse it."""
    problems = []
    for m in TOKEN_RE.finditer(text):          # comments are matched separately, so they are skipped
        if m.group(1):
            for e in re.finditer(r"\\(.)", m.group(1)):
                if e.group(1) not in 'n"\\':
                    line = text.count("\n", 0, m.start()) + 1
                    problems.append("%s line %d: unsupported escape \\%s in %s" % (name, line, e.group(1), m.group(1)[:40]))
    return problems


def cfg_names(items):
    """Names in the CFG table (stride 4: name, default, lowest, highest)."""
    text = dict(items).get("CFG")
    if text is None:
        sys.exit("common.lsl: no CFG table")
    body = text[text.index("[") + 1:text.rindex("]")]
    body = re.sub(r"//[^\n]*", "", body)
    cells = [c.strip() for c in body.split(",") if c.strip()]
    if len(cells) % 4:
        sys.exit("common.lsl: CFG must have 4 entries per setting (name, default, lowest, highest)")
    names = []
    for k in range(0, len(cells), 4):
        name, default, lo, hi = cells[k:k + 4]
        if not (name.startswith('"') and name.endswith('"')):
            sys.exit("common.lsl: CFG entry %d: name must be a string, got %s" % (k // 4, name))
        try:
            d, a, b = float(default), float(lo), float(hi)
        except ValueError:
            sys.exit("common.lsl: CFG %s: default/lowest/highest must be numbers" % name)
        for x in (default, lo, hi):
            if "." not in x:
                sys.exit("common.lsl: CFG %s: write %s as a float (e.g. %s.0) so the list holds floats" % (name, x, x))
        if not a <= d <= b:
            sys.exit("common.lsl: CFG %s: default %s is outside %s..%s" % (name, default, lo, hi))
        names.append(name[1:-1])
    if len(set(names)) != len(names):
        sys.exit("common.lsl: CFG has a duplicate name")
    return names


def check_settings_doc(names):
    """The notecard text must mention every setting once, as 'name = value'."""
    if not os.path.exists(SETTINGS_DOC):
        sys.exit("missing " + SETTINGS_DOC)
    with open(SETTINGS_DOC, encoding="utf-8") as f:
        doc = f.read()
    found = re.findall(r"^\s*([a-z_]+)\s*=", doc, re.M)
    missing = [n for n in names if n not in found]
    unknown = [n for n in found if n not in names]
    dup = sorted({n for n in found if found.count(n) > 1})
    if missing or unknown or dup:
        sys.exit("docs/Wind_Settings.txt is out of step with CFG: missing %s, unknown %s, repeated %s"
                 % (missing, unknown, dup))


def build():
    with open(os.path.join(SRC, "common.lsl"), encoding="utf-8") as f:
        items = parse_common(f.read())
    names = cfg_names(items)
    check_settings_doc(names)
    outputs = []
    print("%-24s %7s %7s" % ("script", "tokens", "shared"))
    for src, out in SCRIPTS.items():
        path = os.path.join(SRC, src)
        if not os.path.exists(path):
            print("skip (missing): " + src)
            continue
        with open(path, encoding="utf-8") as f:
            text = f.read()
        if "// @include common" not in text:
            sys.exit(src + ": missing '// @include common'")
        for used in CFG_USE_RE.findall(text):
            if used not in names:
                sys.exit('%s: Cfg("%s") is not in the CFG table in common.lsl' % (src, used))
        used = shake(items, text.replace("// @include common", ""))
        shared = "// ---- shared helpers (src/common.lsl): only what this script uses ----\n" + "\n\n".join(used)
        full = BANNER.format(src=src) + text.replace("// @include common", shared)
        bad = lint_escapes(src, full)
        if bad:
            sys.exit("\n".join(bad))
        dest = os.path.join(ROOT, out)
        with open(dest, "w", encoding="utf-8") as f:
            f.write(full)
        outputs.append(dest)
        tokens = token_count(full)
        flag = "  <-- large, may run out of memory" if tokens > TOKEN_WARN else ""
        print("%-24s %7d %7d%s" % (out[:-4], tokens, token_count(shared), flag))
    return outputs


def check(files):
    # Strict LSL only: no optimizer extensions that Second Life would reject.
    opts = "-optimize,-ExtendedGlobalExpr,-ExtendedTypeCast,-ExtendedAssignment,-AllowKeyConcat,-AllowMultiStrings,-BreakCont"
    if not os.path.exists(os.path.join(LSLOPT, "main.py")):
        sys.exit("--check needs LSL-PyOptimizer: git clone https://github.com/Sei-Lisa/LSL-PyOptimizer " + LSLOPT)
    failed = False
    for path in files:
        r = subprocess.run(
            [sys.executable, os.path.join(LSLOPT, "main.py"), "-O", opts, "-o", os.devnull, path],
            capture_output=True, text=True)
        status = "ok    " if r.returncode == 0 else "FAILED"
        print(status + " " + os.path.basename(path))
        if r.returncode != 0:
            failed = True
            print(r.stdout + r.stderr)
    return not failed


if __name__ == "__main__":
    built = build()
    if "--check" in sys.argv and not check(built):
        sys.exit(1)
